# -*- coding: utf-8 -*-


import datetime

import sshrc
import sshrc.core.generator
import sshrc.core.lexer
import sshrc.core.parser
import sshrc.utils



HEADER = """
# THIS FILE WAS AUTOGENERATED BY sshrc on {date}.
# IT MAKES NO SENSE TO EDIT IT MANUALLY!
#
# SSHRC FILE: {sshrc_file}
#
# PLEASE VISIT https://github.com/9seconds/sshrc FOR DETAILS.
""".strip() + "\n\n"


def make_header(**kwargs):
    return HEADER.format(
        date=kwargs.get("date", datetime.datetime.now().ctime()),
        sshrc_file=kwargs.get("sshrc_file", "???"))


def parse(content):
    return "\n".join(
        sshrc.core.generator.generate(
            sshrc.core.parser.parse(
                sshrc.core.lexer.lex(
                    content.split("\n")))))
